import { CointestatarioDettaglio } from './cointestatarioDettaglio';
import { TassaDettaglio } from './tassaDettaglio';
import { SpesaDettaglio } from './spesaDettaglio';
import { AffittoDettaglio } from './affittoDettaglio';
import { MutuoDettaglio } from './mutuoDettaglio';
import { DatiCatastaliDettaglio } from './datiCatastaliDettaglio';
import { OmiDettaglio } from './omiDettaglio';

export class ImmobileDettaglio {
    public proprieta_id: number = 0;
    public tipologie_catastali_id: number;
    public codice_fiscale: string = "";
    public codice_tipologia: string = "";
    public descrizione_tipologia: string = "";
    public data_aggiornamento: number = 0;
    public valore_acquisto: number = 0;
    public quota: number = 0;
    public catastale_cod: string = "";
    public comune_zone_cod: string = "";
    public indirizzo: string = "";
    public civico: string = "";
    public citta: string = "";
    public cap: string = "";
    public provincia: string = "";
    public istat_cod: string = "";
    public latitudine: string = "";
    public longitudine: string = "";
    public prima_casa: boolean = false;
    public destinazione_uso_id: number = 0;
    public descrizione_uso: string = "";
    public mutuo: boolean = false;
    public affitto: boolean = false;
    public cointestatari: Array<CointestatarioDettaglio>;
    public tasse: Array<TassaDettaglio>;
    public spese: Array<SpesaDettaglio>;
    public affitto_dettaglio: AffittoDettaglio;
    public mutuo_dettaglio: MutuoDettaglio;
    public dati_catastali: DatiCatastaliDettaglio;
    public omi: OmiDettaglio;
}